image: node:lts

stages:
  - build
  - deploy

before_script:
  - npm ci

build:
  stage: build
  script:
    - echo "Building the project..."
    # Aqui você pode adicionar comandos para compilar ou preparar seu projeto, se necessário.
  artifacts:
    paths:
      - .  # Coloque aqui o caminho para os arquivos que você deseja servir

pages:
  stage: deploy
  script:
    - echo "Deploying your static portfolio..."
    - sed -i 's|old-url.com|https://robinsonmourao.github.io/portifolio/|g' *.html  # Exemplo para HTML
    - mkdir -p public  # Cria a pasta public caso não exista
    - shopt -s extglob  # Ativa a expansão de padrões avançados no bash
    - mv !("public") public/
  artifacts:
    paths:
      - public  # Serve os arquivos da pasta 'public'
  only:
    - main  # Ou a branch que você quiser usar
