# A imagem Docker que será usada para construir seu app
image: node:lts

# Funções que devem ser executadas antes do script de build
before_script:
  - npm ci

# Nome do stage
stages:
  - deploy

# Job para fazer o deploy
deploy:
  stage: deploy
  script:
    - echo "Deploying your static portfolio..."
    - mkdir -p public  # Cria a pasta public se não existir
    - cp -R * public/  # Copia todos os arquivos para a pasta public
  only:
    - main  # Ou a branch que você quiser usar
  environment:
    name: production
    url: http://robinsonmourao.portifolio.com
  artifacts:
    paths:
      - public/  # A pasta pública que o GitLab Pages vai servir

# Configuração para GitLab Pages
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
    - cp -R * public/  # Copia os arquivos para a pasta padrão do GitLab Pages
  artifacts:
    paths:
      - public  # A pasta pública que o GitLab Pages vai servir
  only:
    - main  # Ou a branch que você quiser usar
