# A imagem Docker que será usada para construir seu app
image: node:lts

# Funções que devem ser executadas antes do script de build
before_script:
  - npm ci  # Instala as dependências do Node.js

# Job para fazer o deploy
pages:
  stage: deploy
  script:
    - echo "Deploying your static portfolio..."
  artifacts:
    paths:
      - .  # Serve os arquivos da pasta public
  only:
    - main  # Ou a branch que você quiser usar
