# A imagem Docker que será usada para construir seu app
image: node:lts

# Nome do stage
stages:
  - deploy

# Job para fazer o deploy
pages:
  stage: deploy
  script:
    - echo "Deploying your static portfolio..."
  artifacts:
    paths:
      - / # Serve os arquivos do diretório 'public'
  only:
    - main  # Ou a branch que você quiser usar
