# A imagem Docker que será usada para construir seu app
image: node:lts

# Funções que devem ser executadas antes do script de build
before_script:
  - npm ci

# Nome do stage
stages:
  - deploy

# Job para fazer o deploy
pages:
  stage: deploy
  script:
    - echo "Deploying your static portfolio..."
  artifacts:
    paths:
      - .  # Serve os arquivos do diretório atual
  only:
    - main  # Ou a branch que você quiser usar
